# Generated by Django 4.2.17 on 2025-03-29 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_rating_options_rating_is_approved_rating_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('passenger_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='trip.booking')),
            ],
        ),
    ]
