# Generated by Django 4.2.17 on 2025-03-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='context',
            field=models.TextField(blank=True, help_text='Dynamic data to display in the card template (JSON string)', null=True),
        ),
    ]
