# Generated by Django 4.2.17 on 2025-04-27 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='senior_fare_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='senior_passengers',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_fare_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='student_passengers',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='senior_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Senior citizen fare rate (with valid ID)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='student_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Student fare rate (with valid ID)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passenger_type',
            field=models.CharField(choices=[('adult', 'Regular Adult'), ('child', 'Child'), ('student', 'Student'), ('senior', 'Senior Citizen')], default='adult', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='adult_fare',
            field=models.DecimalField(decimal_places=2, help_text='Regular adult passenger fare rate', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
